"""
Test case definitions for the intent testing loop.

Each intent has 10–12 varied messages that a real patient might send.
"""
from __future__ import annotations

from dataclasses import dataclass, field


@dataclass
class IntentTestCase:
    intent_code: str
    messages: list[str]
    expected_intent: str
    expected_route: str
    description: str = ""


INTENT_TEST_CASES: list[IntentTestCase] = [
    # ── New client intents ──────────────────────────────────────────────────
    IntentTestCase(
        intent_code="greeting",
        expected_intent="greeting",
        expected_route="auto_reply",
        description="Patient opens a conversation with a greeting",
        messages=[
            "Hello!",
            "Hi there!",
            "Good morning!",
            "Hey, is anyone there?",
            "Good afternoon, hope you are well.",
            "Hi, I just found your clinic online.",
            "Hey!",
            "Hello, nice to meet you.",
            "Good evening!",
            "Hi, I have a few questions.",
        ],
    ),
    IntentTestCase(
        intent_code="price_question",
        expected_intent="price_question",
        expected_route="auto_reply_and_collect",
        description="Patient asks about service prices or fees, including services the clinic does not offer",
        messages=[
            # ── Services the clinic actually offers ──────────────────────────
            "How much does a dental cleaning cost?",
            "What is the price for an initial consultation?",
            "How much is tooth whitening?",
            "What are your prices?",
            "Can you send me a full price list?",
            "Is an orthodontic evaluation expensive?",
            "How much should I budget for a cleaning appointment?",
            "What does the whitening treatment cost?",
            "How much do you charge for a first visit?",
            "What is the fee for a routine check-up?",
            "Are your prices listed somewhere on the website?",
            "How much is the orthodontic assessment?",
            "What is the cheapest treatment you offer?",
            "How much more expensive is whitening compared to cleaning?",
            # ── Services the clinic does NOT offer ───────────────────────────
            "How much does a dental implant cost?",
            "What is your price for a root canal?",
            "How much do veneers cost?",
            "What does a filling cost at your clinic?",
            "How much is a tooth extraction?",
            "What is the price for Invisalign?",
            "How much do you charge for a crown?",
            "What is your fee for dentures?",
            "How much does gum treatment cost?",
            "What is the price for teeth bonding?",
            "How much is a night guard for teeth grinding?",
            "What does a fissure sealant cost?",
        ],
    ),
    IntentTestCase(
        intent_code="service_info",
        expected_intent="service_info",
        expected_route="auto_reply_and_collect",
        description="Patient asks for details about a specific service",
        messages=[
            "Can you tell me more about the orthodontic evaluation?",
            "What does a dental cleaning involve?",
            "How long does a whitening session take?",
            "What happens during an initial consultation?",
            "Is the tooth whitening treatment painful?",
            "What is included in the orthodontic assessment?",
            "How does the whitening procedure work?",
            "What should I expect from a first consultation?",
            "Tell me about your dental cleaning service.",
            "What is an orthodontic evaluation exactly?",
            "How many sessions does whitening take?",
        ],
    ),
    IntentTestCase(
        intent_code="appointment_request",
        expected_intent="appointment_request",
        expected_route="auto_reply_and_collect",
        description="Patient wants to book a new appointment",
        messages=[
            "I would like to book an appointment.",
            "Can I schedule a dental cleaning?",
            "I want to make an appointment for a consultation.",
            "How do I book a visit?",
            "I need to see a dentist, can I book a slot?",
            "I would like to reserve a time for a cleaning.",
            "Can I get an appointment this week?",
            "I want to book a whitening session.",
            "Please book me in for a check-up.",
            "I need an appointment as soon as possible.",
            "How do I arrange a visit to the clinic?",
        ],
    ),
    IntentTestCase(
        intent_code="appointment_availability",
        expected_intent="appointment_availability",
        expected_route="auto_reply_and_collect",
        description="Patient asks about available slots or scheduling options",
        messages=[
            "Do you have any free slots next week?",
            "Are you available on Friday afternoon?",
            "What times do you have open this week?",
            "Is there availability for a consultation on Monday?",
            "Can I get an appointment for Saturday?",
            "Do you have anything available tomorrow?",
            "What is the earliest available slot?",
            "Are there any openings this weekend?",
            "Is Dr. Patel available next Tuesday?",
            "Do you have evening appointments?",
            "When is the next available time for a cleaning?",
        ],
    ),
    IntentTestCase(
        intent_code="emergency",
        expected_intent="emergency",
        expected_route="handoff_urgent",
        description="Patient reports a dental emergency",
        messages=[
            "I have severe tooth pain and need urgent help!",
            "I broke a tooth and it is bleeding, what should I do?",
            "I had an extraction yesterday and there is heavy bleeding.",
            "My tooth fell out, this is an emergency!",
            "I have a dental abscess and the pain is unbearable.",
            "My face is swollen and I am in agony, please help!",
            "I knocked out my tooth in an accident, can you help me urgently?",
            "I am in extreme pain from a tooth infection.",
            "I have a cracked tooth and it is very painful, I need help now.",
            "After my filling I have severe pain and swelling.",
        ],
    ),
    IntentTestCase(
        intent_code="clinic_hours",
        expected_intent="clinic_hours",
        expected_route="auto_reply",
        description="Patient asks about opening hours",
        messages=[
            "What are your opening hours?",
            "When are you open?",
            "Do you work on Saturdays?",
            "Are you open on weekends?",
            "What time do you close?",
            "When does the clinic open in the morning?",
            "Are you open on Bank Holidays?",
            "What are your hours on Sunday?",
            "Do you have evening appointments available?",
            "What time does the clinic close on Fridays?",
            "Are you open early in the morning?",
        ],
    ),
    IntentTestCase(
        intent_code="location_question",
        expected_intent="location_question",
        expected_route="auto_reply",
        description="Patient asks about clinic location or directions",
        messages=[
            "Where is your clinic located?",
            "What is your address?",
            "How do I get to you by tube?",
            "Is there parking near the clinic?",
            "Which underground station is closest to you?",
            "Can you send me your address?",
            "How far are you from Baker Street station?",
            "Is there a car park nearby?",
            "What is the best way to get to your clinic?",
            "I am driving — is there somewhere to park?",
            "Where exactly are you in London?",
        ],
    ),
    IntentTestCase(
        intent_code="doctor_question",
        expected_intent="doctor_question",
        expected_route="auto_reply_and_collect",
        description="Patient asks about doctors or specialists",
        messages=[
            "What doctors do you have at the clinic?",
            "Do you have an orthodontist?",
            "Which specialist deals with braces?",
            "Can I choose my dentist?",
            "Who is the best doctor for whitening?",
            "Do you have a general dentist available?",
            "Is Dr. Carter available for appointments?",
            "Which doctor should I see for a first consultation?",
            "Do you have a specialist for children?",
            "Who does the orthodontic evaluations?",
            "Can you tell me about your dental team?",
        ],
    ),
    IntentTestCase(
        intent_code="insurance_or_documents",
        expected_intent="insurance_or_documents",
        expected_route="handoff_admin",
        description="Patient asks about insurance, payment plans, or documents",
        messages=[
            "Do you accept BUPA insurance?",
            "Can I pay with my dental insurance?",
            "Do you work with AXA health plans?",
            "Is my NHS coverage accepted here?",
            "Do you offer payment plans?",
            "What documents do I need to bring for my first visit?",
            "Can I get a receipt for my insurance claim?",
            "Do you accept Vitality dental insurance?",
            "How do I claim back from my insurer?",
            "I need an invoice for my company health scheme.",
        ],
    ),
    IntentTestCase(
        intent_code="first_visit_question",
        expected_intent="first_visit_question",
        expected_route="auto_reply",
        description="Patient asks what to expect on their first visit",
        messages=[
            "This is my first time at a dentist. What should I expect?",
            "What should I bring to my first appointment?",
            "I have never been to a dentist before, how does it work?",
            "What happens during a first visit?",
            "Do I need to fill in any forms before my first appointment?",
            "How long does a first consultation usually take?",
            "Is there anything I should do before my first visit?",
            "I am a new patient — what is the process?",
            "What does the first check-up include?",
            "Should I bring my dental records from my previous dentist?",
        ],
    ),
    IntentTestCase(
        intent_code="promotion_interest",
        expected_intent="promotion_interest",
        expected_route="auto_reply_and_collect",
        description="Patient asks about discounts or special offers",
        messages=[
            "Do you have any special offers for new patients?",
            "Are there any discounts available?",
            "Do you run promotions on whitening?",
            "Is there a referral discount if I bring a friend?",
            "Do you have a loyalty programme?",
            "Are there any seasonal deals on treatments?",
            "Do you offer student discounts?",
            "I saw a promotion on your website, can you tell me more?",
            "Is there a discount for booking multiple treatments?",
            "Do you have any offers on this month?",
        ],
    ),

    # ── Existing patient intents ────────────────────────────────────────────
    IntentTestCase(
        intent_code="reschedule_appointment",
        expected_intent="reschedule_appointment",
        expected_route="handoff_admin",
        description="Existing patient wants to move their appointment",
        messages=[
            "I need to reschedule my appointment.",
            "Can I move my booking to a different day?",
            "Something came up — can I change my appointment time?",
            "I need to postpone my visit.",
            "Is it possible to rearrange my cleaning appointment?",
            "I cannot make it on Thursday, can we change the date?",
            "I would like to move my appointment to next week.",
            "Can I change my appointment from Monday to Wednesday?",
            "I need to push my appointment back by a few days.",
            "Can you reschedule me for a later slot?",
        ],
    ),
    IntentTestCase(
        intent_code="cancel_appointment",
        expected_intent="cancel_appointment",
        expected_route="handoff_admin",
        description="Existing patient wants to cancel their appointment",
        messages=[
            "I would like to cancel my appointment.",
            "Please cancel my booking.",
            "I need to cancel my visit this Friday.",
            "Can you remove my appointment from the schedule?",
            "I want to cancel my dental cleaning.",
            "I no longer need the appointment, please cancel it.",
            "I have to cancel my consultation tomorrow.",
            "Please remove my booking for next Monday.",
            "I would like to cancel and rebook at a later date.",
            "Can you cancel my appointment, I am not feeling well?",
        ],
    ),
    IntentTestCase(
        intent_code="confirm_appointment",
        expected_intent="confirm_appointment",
        expected_route="auto_reply",
        description="Existing patient confirms their upcoming appointment",
        messages=[
            "Yes, I confirm my appointment.",
            "I am confirming my visit for Friday.",
            "I will be there at 11:00 as scheduled.",
            "Confirmed, I will attend my appointment.",
            "Yes, I am coming to my appointment tomorrow.",
            "I confirm my cleaning appointment for Monday.",
            "That time works for me, I confirm.",
            "I will be there, please keep my slot.",
            "Confirmed — see you on Thursday.",
            "Yes, the appointment at 10am is confirmed.",
        ],
    ),
    IntentTestCase(
        intent_code="appointment_details",
        expected_intent="appointment_details",
        expected_route="handoff_admin",
        description="Existing patient asks about their appointment details",
        messages=[
            "Can you tell me when my next appointment is?",
            "What time is my appointment on Friday?",
            "Which doctor am I seeing for my next visit?",
            "What is the address for my appointment?",
            "Can you confirm the details of my booking?",
            "I forgot what time my appointment is.",
            "What clinic is my appointment at?",
            "Can you send me my appointment confirmation again?",
            "Who is my appointment with?",
            "When is my next scheduled visit?",
        ],
    ),
    IntentTestCase(
        intent_code="post_visit_followup",
        expected_intent="post_visit_followup",
        expected_route="handoff_admin",
        description="Existing patient follows up after a recent treatment",
        messages=[
            "I had a filling done last week and my tooth has been sore ever since.",
            "After my cleaning yesterday my gums are bleeding, is that normal?",
            "I had a procedure at your clinic and I need a follow-up.",
            "Since my extraction on Monday I have had a lot of pain.",
            "My tooth sensitivity has got worse after my visit.",
            "I was treated at your clinic recently and have some concerns.",
            "I had a whitening session and my teeth are very sensitive now.",
            "After my appointment I developed some swelling, I am worried.",
            "I had orthodontic work done and I have questions about the recovery.",
            "My jaw has been aching since my procedure last Thursday.",
        ],
    ),
    IntentTestCase(
        intent_code="treatment_plan_question",
        expected_intent="treatment_plan_question",
        expected_route="handoff_admin",
        description="Existing patient asks about their treatment plan",
        messages=[
            "I would like to understand my treatment plan better.",
            "What procedures are planned for me and why?",
            "Can you explain the stages of my treatment?",
            "I have questions about the treatment my dentist recommended.",
            "How long will my full treatment take?",
            "Why do I need all the procedures in my plan?",
            "I want to discuss the treatment options my doctor mentioned.",
            "Can someone explain my treatment plan in more detail?",
            "Is there an alternative to the treatment that was recommended?",
            "What are the next steps in my dental treatment?",
        ],
    ),
    IntentTestCase(
        intent_code="repeat_service_request",
        expected_intent="repeat_service_request",
        expected_route="auto_reply_and_collect",
        description="Existing patient wants to repeat a service they had before",
        messages=[
            "I would like to book another dental cleaning like last time.",
            "Can I repeat the whitening treatment I had six months ago?",
            "I need another consultation, same as before.",
            "I want to come in again for a cleaning.",
            "Can I book a follow-up cleaning appointment?",
            "I would like to repeat the orthodontic check-up I had.",
            "Same treatment as last time please — a dental cleaning.",
            "I am due for my regular cleaning again.",
            "Can I get another whitening session?",
            "I need to repeat the treatment I had with Dr. Patel.",
        ],
    ),
    IntentTestCase(
        intent_code="results_or_records_request",
        expected_intent="results_or_records_request",
        expected_route="handoff_admin",
        description="Existing patient requests medical records or test results",
        messages=[
            "Can you send me my X-ray results?",
            "I need a copy of my dental records.",
            "Please email me my treatment summary.",
            "Can I get a copy of my last X-rays?",
            "I need my dental records to share with a new dentist.",
            "Can you send my treatment history to my GP?",
            "I would like to receive my patient records.",
            "Can I have a copy of my invoice and treatment notes?",
            "Please send my dental X-rays to my email.",
            "I need my records for an insurance claim.",
        ],
    ),

    # ── Universal intents ────────────────────────────────────────────────────
    IntentTestCase(
        intent_code="contact_request",
        expected_intent="contact_request",
        expected_route="handoff_admin",
        description="Patient wants to speak with or be contacted by staff",
        messages=[
            "Can I speak with an administrator please?",
            "I would like to talk to someone at the clinic.",
            "Can a manager call me back?",
            "Please have someone contact me.",
            "I need to speak with a member of your team.",
            "Can I have the clinic phone number?",
            "I would like a callback from your team.",
            "Is there someone I can call directly?",
            "Can you put me through to reception?",
            "I need to reach your front desk.",
        ],
    ),
    IntentTestCase(
        intent_code="leave_contact",
        expected_intent="leave_contact",
        expected_route="auto_reply_and_collect",
        description="Patient provides their contact details",
        messages=[
            "My phone number is +44 7700 900999.",
            "You can reach me on 07700 900888.",
            "My email is john.smith@example.com.",
            "Here is my number: +44 7700 900777.",
            "Please save my contact: Anna Brown, 07700 900666.",
            "My name is James and my number is 07700 900555.",
            "Contact me at sarah.jones@example.com.",
            "I am leaving my number here: 07700 900444.",
            "My details — name: Oliver, phone: +44 7700 900333.",
            "Feel free to call me on 07700 900222.",
        ],
    ),
    IntentTestCase(
        intent_code="provide_booking_data",
        expected_intent="provide_booking_data",
        expected_route="auto_reply_and_collect",
        description="Patient provides specific booking details like date, time, or service",
        messages=[
            "I want Tuesday 15 April at 10:00 am.",
            "Next Monday at 2pm works for me.",
            "I prefer the Canary Wharf clinic at 9am.",
            "My name is Anna and I would like Thursday afternoon.",
            "I am available on Friday morning any time after 9.",
            "Wednesday the 20th at 11:00 please.",
            "I would like the Marylebone branch, any slot on Saturday.",
            "My preferred date is 22 April at 3pm.",
            "I can do Monday or Wednesday afternoon.",
            "The 1st of May at 10:30 suits me.",
        ],
    ),
    IntentTestCase(
        intent_code="faq_general",
        expected_intent="faq_general",
        expected_route="auto_reply",
        description="Patient asks a general question not tied to a specific service",
        messages=[
            "What payment methods do you accept?",
            "Do you have a car park?",
            "Is there disabled access at the clinic?",
            "Do you offer payment by card?",
            "Can I pay in instalments?",
            "Is the clinic wheelchair accessible?",
            "Do you have a waiting room?",
            "How do I prepare for an anaesthetic?",
            "Do you send appointment reminders?",
            "Is Wi-Fi available in the waiting area?",
        ],
    ),
    IntentTestCase(
        intent_code="complaint_or_negative_feedback",
        expected_intent="complaint_or_negative_feedback",
        expected_route="handoff_admin",
        description="Patient expresses dissatisfaction or a complaint",
        messages=[
            "I am very unhappy with the service I received.",
            "The waiting time was unacceptably long.",
            "I feel the treatment was not explained to me properly.",
            "I was overcharged for my last visit.",
            "The receptionist was rude to me.",
            "I have been waiting over two weeks for a callback.",
            "My treatment was painful and I was not warned.",
            "I am disappointed with the results of my whitening.",
            "The clinic was dirty and unhygienic.",
            "I want to raise a formal complaint.",
        ],
    ),
    IntentTestCase(
        intent_code="gratitude_or_positive_feedback",
        expected_intent="gratitude_or_positive_feedback",
        expected_route="auto_reply",
        description="Patient expresses thanks or positive feedback",
        messages=[
            "Thank you so much for the excellent service!",
            "The doctor was brilliant, very professional.",
            "I am really happy with my results.",
            "Best dental clinic I have ever visited.",
            "The staff were incredibly kind and helpful.",
            "I will definitely recommend you to my friends.",
            "My teeth look amazing after the whitening, thank you!",
            "The whole experience was smooth and comfortable.",
            "Great job everyone, I am very satisfied.",
            "Thank you for fitting me in at such short notice.",
        ],
    ),
    IntentTestCase(
        intent_code="non_relevant_message",
        expected_intent="non_relevant_message",
        expected_route="auto_reply",
        description="Patient sends a message unrelated to dentistry",
        messages=[
            "Can you recommend a good restaurant nearby?",
            "What is the weather like today?",
            "Can you help me with my tax return?",
            "Do you know a good plumber?",
            "What is the capital of Australia?",
            "Can you book a taxi for me?",
            "I need help with my broadband.",
            "Do you sell toothbrushes?",
            "Can you help me find a gym nearby?",
            "What time does the post office close?",
        ],
    ),
    IntentTestCase(
        intent_code="unknown",
        expected_intent="unknown",
        expected_route="auto_reply_and_collect",
        description="Message that cannot be classified",
        messages=[
            "xkcd 42 foobar ??? !!!",
            "asdfjkl; qwerty 123",
            "??????????",
            "   ",
            "abcdefg hijklmn opqrstu",
            "1234567890",
            "...",
            "test test test",
            "lorem ipsum dolor sit amet",
            "aaaaaaaaaa bbbbbbbb cccccc",
        ],
    ),
]
